// FIXED: BLOCKER_3 — Centralized config for all extension URLs
// Set IS_DEV to true for local development, false for production/Chrome Web Store
const DARKSCAN_CONFIG = {
  PROD_API_URL: 'https://YOUR_DEPLOYED_BACKEND_DOMAIN/api/v1/analyze',
  PROD_WS_URL: 'wss://YOUR_DEPLOYED_BACKEND_DOMAIN/ws',
  PROD_DASHBOARD_URL: 'https://YOUR_DEPLOYED_BACKEND_DOMAIN',
  DEV_API_URL: 'http://localhost:5000/api/v1/analyze',
  DEV_WS_URL: 'ws://localhost:5000/ws',
  DEV_DASHBOARD_URL: 'http://localhost:5000',
  IS_DEV: true
};
const API_URL = DARKSCAN_CONFIG.IS_DEV ? DARKSCAN_CONFIG.DEV_API_URL : DARKSCAN_CONFIG.PROD_API_URL;
const WS_URL = DARKSCAN_CONFIG.IS_DEV ? DARKSCAN_CONFIG.DEV_WS_URL : DARKSCAN_CONFIG.PROD_WS_URL;
const DASHBOARD_URL = DARKSCAN_CONFIG.IS_DEV ? DARKSCAN_CONFIG.DEV_DASHBOARD_URL : DARKSCAN_CONFIG.PROD_DASHBOARD_URL;
