import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

export const generatePdfReport = async (audit) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Custom colors matching theme
  const bg = '#0A0A0A';
  const text = '#F5F5F0';
  const gold = '#C9A96E';
  
  // Helper for background
  const setDarkBackground = () => {
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
  };

  // --- Page 1: Cover ---
  setDarkBackground();
  
  // Title
  doc.setTextColor(201, 169, 110); // Gold
  doc.setFont('helvetica', 'normal'); // fallback for Playfair
  doc.setFontSize(28);
  doc.text('DarkScan Audit Report', pageWidth / 2, 60, { align: 'center' });
  
  doc.setTextColor(245, 245, 240); // White
  doc.setFontSize(14);
  doc.text(`Target: ${audit.url}`, pageWidth / 2, 80, { align: 'center' });
  doc.text(`Date: ${new Date(audit.timestamp).toLocaleString()}`, pageWidth / 2, 90, { align: 'center' });
  
  // Score presentation
  doc.setDrawColor(201, 169, 110);
  doc.setLineWidth(2);
  doc.circle(pageWidth / 2, 140, 30);
  
  doc.setFontSize(36);
  doc.text(Math.round(audit.overallScore).toString(), pageWidth / 2, 145, { align: 'center' });
  
  doc.setFontSize(16);
  doc.text(audit.severityLevel.toUpperCase(), pageWidth / 2, 185, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(160, 160, 154);
  doc.text('Confidential AI-Generated Manipulation Analysis', pageWidth / 2, 250, { align: 'center' });
  
  // --- Page 2: Summary ---
  doc.addPage();
  setDarkBackground();
  
  doc.setTextColor(201, 169, 110);
  doc.setFontSize(22);
  doc.text('Executive Summary', 20, 30);
  
  doc.setTextColor(245, 245, 240);
  doc.setFontSize(12);
  const summaryText = `This report details the automated analysis of ${new URL(audit.url).hostname}. The multi-modal detection engine identified ${audit.detectedPatterns?.length || 0} potential dark patterns. The overall manipulation index is ${Math.round(audit.overallScore)}/100, classified as ${audit.severityLevel}.`;
  
  const splitText = doc.splitTextToSize(summaryText, pageWidth - 40);
  doc.text(splitText, 20, 50);

  // --- Page 3+: Patterns ---
  if (audit.detectedPatterns && audit.detectedPatterns.length > 0) {
    doc.addPage();
    setDarkBackground();
    
    doc.setTextColor(201, 169, 110);
    doc.setFontSize(22);
    doc.text('Detected Patterns Details', 20, 30);
    
    let yPos = 50;
    
    audit.detectedPatterns.forEach((p, idx) => {
      if (yPos > pageHeight - 60) {
        doc.addPage();
        setDarkBackground();
        yPos = 30;
      }
      
      doc.setTextColor(245, 245, 240);
      doc.setFontSize(14);
      doc.text(`${idx + 1}. ${p.category.replace(/_/g, ' ').toUpperCase()}`, 20, yPos);
      
      doc.setFontSize(10);
      doc.setTextColor(160, 160, 154);
      doc.text(`Confidence: ${Math.round(p.confidence * 100)}% | Detectors: ${(p.detectedBy || []).join(', ')}`, 20, yPos + 8);
      
      doc.setTextColor(245, 245, 240);
      const evText = doc.splitTextToSize(`Evidence: ${p.evidenceText || p.domEvidence || 'Visual anomaly detected'}`, pageWidth - 40);
      doc.text(evText, 20, yPos + 18);
      
      if (p.legalClause) {
         doc.setTextColor(201, 169, 110);
         const leText = doc.splitTextToSize(`Regulatory: ${p.legalClause}`, pageWidth - 40);
         doc.text(leText, 20, yPos + 18 + (evText.length * 5) + 5);
         yPos += (leText.length * 5);
      }
      
      yPos += (evText.length * 5) + 35;
    });
  }

  // --- Final Page: Legal ---
  doc.addPage();
  setDarkBackground();
  doc.setTextColor(201, 169, 110);
  doc.setFontSize(22);
  doc.text('Disclaimer & Legal Notation', 20, 30);
  
  doc.setTextColor(160, 160, 154);
  doc.setFontSize(10);
  const legalText = `This report is generated by an automated AI diagnostic system analyzing DOM, NLP, and Visual features. It does not constitute formal legal counsel. Findings mappings to the India DPDP Act 2023 or GDPR are advisory algorithms based on pattern matching.`;
  const splitLegal = doc.splitTextToSize(legalText, pageWidth - 40);
  doc.text(splitLegal, 20, 50);

  // Save
  doc.save(`darkscan-report-${new URL(audit.url).hostname}-${Date.now()}.pdf`);
};
